### PR TITLE
Update to automerge@0.5.0, implement marks

### LINKED ISSUE #21: Update to Automerge 0.4.0
I saw that Automerge-rs released an updated 0.4.0 crate, and went and took a quick stab at updating this repo to use it.

Unfortunately, with the version update there's a few breaking changes to the internal pieces that enable the UniFFI overlay. When I updated to 0.4.0, I received the following errors when invoking `cargo build`:

```
error[E0050]: method `insert` has 5 parameters but the declaration in trait `automerge::OpObserver::insert` has 6
  --> src/patches/observer.rs:90:9
   |
90 | /         &mut self,
91 | |         doc: &R,
92 | |         obj: am::ObjId,
93 | |         index: usize,
94 | |         tagged_value: (am::Value<'_>, am::ObjId),
   | |________________________________________________^ expected 6 parameters, found 5
   |
   = note: `insert` from trait: `fn(&mut Self, &R, automerge::ObjId, usize, (automerge::Value<'_>, automerge::ObjId), bool)`

error[E0046]: not all trait items implemented, missing: `mark`, `unmark`
  --> src/patches/observer.rs:88:1
   |
88 | impl am::OpObserver for Observer {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `mark`, `unmark` in implementation
   |
   = help: implement the missing item: `fn mark<R, M>(&mut self, _: &'a R, _: automerge::ObjId, _: M) where R: ReadDoc, M: Iterator, std::iter::Iterator::Item = automerge::marks::Mark<'a> { todo!() }`
   = help: implement the missing item: `fn unmark<R>(&mut self, _: &R, _: automerge::ObjId, _: &str, _: usize, _: usize) where R: ReadDoc { todo!() }`
```

Since I'm only minimally proficient at Rust, I thought I'd wait until @alexjg was available to help make this migration, as I'm uncertain of the implications as well as implementation changes needed.

### PR DESCRIPTION
**Pull request by alexjg**
There are some mechanical changes to the API:

* Allow negative `delete` arguments for `Doc.splice` and `Doc.spliceText`
* Add `Doc.mark`, `Doc.marks` and `Doc.marksAt`
* Add the `Mark` and `ExpandMark` types
* Add PatchAction.Conflict and PatchAction.Marks
* Add a `marks` field to `PatchAction.SpliceText` and `PatchAction.Insert`

One slightly more significant change is the addition of `unsafe impl Send{}` and `unsafe impl Sync{}` on the `Doc` we export to uniffi. This is required because currently `automerge::Automerge` is not `Send` or `Sync` due to the internal use of an `Rc`. The `unsafe` impls are okay because we guarantee that all accesses of the document on the Swift side are from a single thread. In future we should be able to remove the `Rc` from automerge to make it `Send` again and remove these unsafe impls.

resolves #21

### CODE REVIEW

**Comment by heckj** [comment]
I added two (very small) commits to hopefully resolve the CI issues - one that clean up a bit of extraneous whitespace that `rustfmt` was whinging about, and another that I'm hoping will clear the CI test issues - we'll see after it runs. While I was doing through, I did notice that `clippy` tossed out a warning, but didn't know enough to know if it was important or not, so I'll tack it on here for your looksee:

```
warning: you should consider adding a `Default` implementation for `SyncState`
  --> src/sync_state.rs:16:5
   |
16 | /     pub fn new() -> Self {
17 | |         Self(RwLock::new(am::sync::State::new()))
18 | |     }
   | |_____^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#new_without_default
   = note: `#[warn(clippy::new_without_default)]` on by default
help: try adding this
   |
15 + impl Default for SyncState {
16 +     fn default() -> Self {
17 +         Self::new()
18 +     }
19 + }
   |
```

**Comment by alexjg** [comment]
Thanks for the fixes!

Yeah that particular warning from clippy I find over-zealous. This may just be because I am a bit grumpy about the extensive use of `Default` in the Rust ecosystem, which I consider to be a mistake. In this case it's probably fine though, I'll add an impl just to keep clippy happy :slightly_smiling_face:

**Review by heckj — APPROVED** [review]
I went through and updated the overall documentation to incorporate Marks, and tweaked a few descriptions for consistency and clarity.

This is wonderful, thank you! In a follow-on PR, I'll work on figuring out how a scheme on how to pull common marks (such as bold, italic, and link) and enable some capabilities to return both String and AttributedString with appropriate swift typed annotations of marks.
